<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!--OpenAPI Specification-->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Scalar.AspNetCore.Microsoft" Version="2.17.14" />
  </ItemGroup>
</Project>